# Generated by Django 5.1.5 on 2025-01-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscoordinates',
            name='accuracy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
